"$schema" = 'https://starship.rs/config-schema.json'

format = """
${custom.beginchar}\
$directory\
$os\
$git_branch\
$git_status\
$memory_usage\
$jobs\
$status\
$cmd_duration\
[](fg:color_bg3)\
$fill\
[](fg:color_bg1)\
$time\
[](fg:color_bg1)\
$line_break\
${custom.endchar} \
"""

continuation_prompt = ' '

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg2 = '#555599'
color_bg3 = '#665c54'
color_blue = '#4585aa'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
color_white = '#ffffff'
color_git = '#f56d4e'
color_success = 'green'
color_failure = '#ff5555'
color_duration = '#009900'

#⌈ ⎛ ⎾
#⌊ ⎝ ⎿
#  ▷ ☯  ♺ ♻
[custom.beginchar]
when = true
format = '⎛ '

[custom.endchar]
when = true
format = '⎝ ♺'

[os]
disabled = false
format = '[](color_bg3)[$symbol]($style)'
style = "fg:color_orange bg:color_bg3"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_blue fg:color_fg0"
style_root = "bg:color_blue fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "bold #7777ff"
format = "[ $path ]($style)"
truncation_length = 8
truncation_symbol = "… "
truncate_to_repo = true
#before_repo_root_style = '$style'
#repo_root_style = '$style'
#repo_root_format = '[$repo_root]($repo_root_style)$format[$read_only]($read_only_style) '

[git_branch]
symbol = ""
style = "bg:color_git"
format = """\
[](bg:color_git fg:color_bg3)\
[[ $symbol $branch ](fg:color_fg0 bg:color_git)]($style)\
"""

[git_status]
style = "bg:color_git"
format = '[\[[($all_status$ahead_behind)](fg:color_fg0 bg:color_git)\]]($style)[](fg:color_git bg:color_bg3)'
conflicted = ''
#conflicted = ''
ahead = '${count}⇡'
behind = '${count}⇣'
diverged = '⇕'
#up_to_date = ''
untracked = ' '
stashed = ' '
modified = '${count}'
staged = ' '
renamed = ' »'
deleted = '${count}'

[memory_usage]
disabled = false
threshold = 65
format = '[](fg:color_bg3 bg:color_blue)[ $symbol ${ram}]($style)[](fg:color_blue bg:color_bg3)'
style = 'fg:color_fg0 bg:color_blue'
symbol = '󰍛'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[jobs]
style = "fg:color_fg0 bg:color_bg3"
format = "[$symbol$number ]($style)"
symbol = ''
number_threshold = 1

[fill]
disabled = false
symbol = '─'
style = 'fg:color_bg3'
#style = '#555599'

[time]
disabled = false
time_format = "%F %R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[status]
disabled = false
#format = '[ $symbol ](bg:color_bg3)'
format = '[ $symbol]($style)'
style = 'fg:color_failure bg:color_bg3'
symbol = '${status}${signal_name}'
signal_symbol = '⚡'
#success_symbol = '[](fg:color_success bg:color_bg3)'
#error_symbol = '[](fg:bold red bg:color_bg3)'

[cmd_duration]
disabled = false
format = """
[](fg:color_bg3 bg:color_duration)\
[  $duration]($style)\
[](fg:color_duration bg:color_bg3)\
"""
style = 'fg:color_fg0 bg:color_duration'
min_time = 15_000
show_notifications = true
min_time_to_notify = 90_000
notification_timeout = 10_000
