"$schema" = 'https://starship.rs/config-schema.json'

# See https://github.com/starship/starship/discussions/1107#discussioncomment-11666645

format = """
$directory\
\
$fill\
\
$git_branch\
$git_status\
\
$docker_context\
$golang\
$nodejs\
$python\
$rust\
$c\
$cpp\
$lua\
\
$cmd_duration\
$jobs\
$status\
$memory_usage\
$localip\
$username\
$line_break\
$character\
"""

palette = 'custom'
add_newline = true

[palettes.custom]
#foreground = '#222222'
foreground = '#CCCCCC'
background = '#1E1E2E'
current_line = '#777777'
primary = '#313244'
box = '#333333'
blue = '#8AADF4'
cyan = '#76E3F6'
green = '#A6E3A1'
orange = '#FFAF74'
pink = '#F5BDE6'
purple = '#CBA6F7'
red = '#F38BA8'
yellow = '#F9E2AF'
status = "#e23140"

[palettes.catppuccin_mocha]
foreground = '#D9E0EE'
background = '#1E1E2E'
current_line = '#2E2E3E'
primary = '#313244'
box = '#2E2E3E'
blue = '#8AADF4'
cyan = '#76E3F6'
green = '#A6E3A1'
orange = '#F9AF74'
pink = '#F5BDE6'
purple = '#CBA6F7'
red = '#F38BA8'
yellow = '#F9E2AF'
status = "#e23140"

[palettes.tokyo_night]
foreground = '#D8D8D8'
background = '#1A1B26'
current_line = '#2A2C37'
primary = '#292E42'
box = '#2A2C37'
blue = '#7AA2F7'
cyan = '#7FDBCA'
green = '#98C379'
orange = '#FF9E64'
pink = '#FF75A0'
purple = '#BB80B3'
red = '#F7768E'
yellow = '#E5C07B'
status = "#e23140"

[os]
format = '(fg:current_line)[](fg:red)[$symbol ](fg:primary bg:red)[](fg:red)'
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[directory]
#format = '[](fg:pink)[󰷏 ](fg:primary bg:pink)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[](fg:box)'
format = '[ ](fg:blue)[$read_only$truncation_symbol$path](fg:blue)'
home_symbol = "~"
truncate_to_repo = false
truncation_length = 99
##truncation_symbol = ' '
##read_only = '󱧵 '
##read_only_style = ''

[git_branch]
format = ' (fg:current_line)[](fg:orange)[$symbol](fg:primary bg:orange)[ $branch ](fg:foreground bg:box)'
symbol = " "

[git_status]
format = '[$all_status](fg:orange bg:box)[](fg:box)'
conflicted = ''
up_to_date = ''
untracked = ''
stashed = ''
staged = ' ${count}'
deleted = ' ${count}'
modified = ' ${count}'
renamed = ' ${count}'
diverged = '⇕'
#ahead = ' ⇡${count}'
#diverged = ' ⇕⇡${ahead_count}⇣${behind_count}'
#behind = ' ⇣${count}'

[docker_context]
format = ' (fg:current_line)[](fg:blue)[$symbol](fg:primary bg:blue)[ $context](fg:foreground bg:box)[](fg:box)'
symbol = ' '
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile', 'compose.yaml']
disabled = false

[nodejs]
format = ' (fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = '󰎙 '

[rust]
format = ' (fg:current_line)[](fg:yellow)[$symbol](fg:primary bg:yellow)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' '

[python]
format = ' (fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[ (${version})](fg:foreground bg:box)[](fg:box)'
symbol = ' '

[java]
format = ' (fg:current_line)[](fg:red)[$symbol](fg:primary bg:red)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' '

[golang]
format = ' (fg:current_line)[](fg:red)[$symbol](fg:primary bg:red)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' '

[c]
format = ' (fg:current_line)[](fg:blue)[$symbol](fg:primary bg:blue)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' '

[cpp]
format = ' (fg:current_line)[](fg:blue)[$symbol](fg:primary bg:blue)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' '

[lua]
format = ' (fg:current_line)[](fg:blue)[$symbol](fg:primary bg:blue)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' '

[fill]
#symbol = '─'
symbol = ' '
style = 'fg:current_line'

[status]
format = " (fg:current_line)[](fg:status)[ ](fg:primary bg:status)[ $status $signal_name](fg:foreground bg:box)[](fg:box)"
recognize_signal_code = true
pipestatus = true
pipestatus_separator = "-"
pipestatus_segment_format = "$status"
pipestatus_format = " (fg:current_line)[](fg:status)[ ](fg:primary bg:status)[ ](fg:status bg:box)[ $pipestatus](fg:foreground bg:box)[](fg:box)"
disabled = false

[cmd_duration]
min_time = 1000
format = ' (fg:current_line)[](fg:orange)[ ](fg:primary bg:orange)[ $duration](fg:foreground bg:box)[](fg:box)'

[localip]
format = ' (fg:current_line)[ $localipv4 ]($style)'
ssh_only = false
disabled = true

[time]
format = ' (fg:current_line)[](fg:purple)[󰦖 ](fg:primary bg:purple)[ $time](fg:foreground bg:box)[](fg:box)'
time_format = '%H:%M'
#time_format = "%F %R"
disabled = false

[username]
format = ' (fg:current_line)[](fg:yellow)[](fg:primary bg:yellow)[ ](fg:yellow bg:box)[$user](fg:foreground bg:box)[](fg:box) '
show_always = true
disabled = true

[character]
format = """
[$symbol](fg:current_line) """
success_symbol = '[](fg:bold white)'
error_symbol = '[](fg:bold red)'

[profiles]
transient = """$character"""
